language: python

python:
  - 3.6

services:
  - docker

before_install:
  - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
  - ./pull.sh
  - docker images
  - ./build.sh

install:
  - pip install -r requirements.txt

script:
  - pytest -s

after_success:
  - ./push.sh

after_script:
  - ls -la -R /tmp