sudo: required

language: python

python:
  - 3.6

services:
  - docker

before_install:
  - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
  - ./pull.sh
  - ./build.sh
  - ./push.sh

install:
  - sudo pip install -r requirements.txt

script:
  - sudo pytest
