language: python

python:
  - 3.6

services:
  - docker

before_install:
  - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
  - ./pull.sh
  - ./build.sh
  - ./push.sh

install:
  - pip install -r requirements.txt

script:
  - "travis_wait 30 sleep 1800 &"
  - pytest -s

after_script:
  - ls -la -R /tmp